### ISSUE TITLE
Unsupported texture type: 755564544 | UnboundLocalError: local variable 'texData' referenced before assignment

### ISSUE THREAD

**Issue by pelmentor** [alphazolam/fmt_nd_pak#4]
Hello, when loading any model with Load Textures checked, human or simple prop - no matter, it pops this error. Game is TLOUP1.

Error: Unsupported texture type: 755564544  
Traceback (most recent call last):
  File "E:\Games\The last of Us. Part 1\_EXTRACT\noesisv4473\plugins\python\fmt_nd_pak.py", line 2721, in pakLoadModel
    pak.loadGeometry()
  File "E:\Games\The last of Us. Part 1\_EXTRACT\noesisv4473\plugins\python\fmt_nd_pak.py", line 2514, in loadGeometry
    tex = self.loadVRAM(self.vrams[vramHash][0])
  File "E:\Games\The last of Us. Part 1\_EXTRACT\noesisv4473\plugins\python\fmt_nd_pak.py", line 1784, in loadVRAM
    return NoeTexture(texFileName, width, height, texData, noesis.NOESISTEX_RGBA32)
UnboundLocalError: local variable 'texData' referenced before assignment

**Comment by Jmvars** [comment]
I get this as well. There was a fix suggestion in [this issue](https://github.com/alphazolam/fmt_nd_pak/issues/1#issuecomment-1562428855) but that did not work. At this point I'm trying to extract the model and get the textures separately but I have no idea how to do that.

**Comment by pelmentor** [comment]
> I get this as well. There was a fix suggestion in [this issue](https://github.com/alphazolam/fmt_nd_pak/issues/1#issuecomment-1562428855) but that did not work. At this point I'm trying to extract the model and get the textures separately but I have no idea how to do that.

In the end I just exported textures with ninja ripper.

**Comment by Jmvars** [comment]
> > I get this as well. There was a fix suggestion in [this issue](https://github.com/alphazolam/fmt_nd_pak/issues/1#issuecomment-1562428855) but that did not work. At this point I'm trying to extract the model and get the textures separately but I have no idea how to do that.
> 
> In the end I just exported textures with ninja ripper.

I found a texture extractor and used that, so I'm good now as well.
